// SPDX-License-Identifier: MIT

/* 
 * Retrieve and print ODBC driver information using SQLGetInfo
 *
 * Copyright (c) 2025 Giuseppe Di Terlizzi
 */

#include <inttypes.h>
#include <sql.h>
#include <sqlext.h>
#include <stdio.h>
#include <string.h>

typedef enum { SQLINFO_TYPE_STRING, SQLINFO_TYPE_INT, SQLINFO_TYPE_BOOL, SQLINFO_TYPE_BITMASK } SQLINFO_TYPE;

typedef struct {
    SQLUSMALLINT code;
    SQLCHAR* name;
    SQLINFO_TYPE type;
} SQLInfoItem;

SQLInfoItem items[] = {
    {SQL_ACCESSIBLE_PROCEDURES, "SQL_ACCESSIBLE_PROCEDURES", SQLINFO_TYPE_BOOL},
    {SQL_ACCESSIBLE_TABLES, "SQL_ACCESSIBLE_TABLES", SQLINFO_TYPE_BOOL},
    {SQL_ACTIVE_CONNECTIONS, "SQL_ACTIVE_CONNECTIONS", SQLINFO_TYPE_INT},
    {SQL_ACTIVE_ENVIRONMENTS, "SQL_ACTIVE_ENVIRONMENTS", SQLINFO_TYPE_INT},
    {SQL_ACTIVE_STATEMENTS, "SQL_ACTIVE_STATEMENTS", SQLINFO_TYPE_INT},
    {SQL_AGGREGATE_FUNCTIONS, "SQL_AGGREGATE_FUNCTIONS", SQLINFO_TYPE_BITMASK},
    {SQL_ALTER_DOMAIN, "SQL_ALTER_DOMAIN", SQLINFO_TYPE_BITMASK},
    {SQL_ALTER_TABLE, "SQL_ALTER_TABLE", SQLINFO_TYPE_BITMASK},
    {SQL_ASYNC_MODE, "SQL_ASYNC_MODE", SQLINFO_TYPE_INT},
    {SQL_BATCH_ROW_COUNT, "SQL_BATCH_ROW_COUNT", SQLINFO_TYPE_INT},
    {SQL_BATCH_SUPPORT, "SQL_BATCH_SUPPORT", SQLINFO_TYPE_BITMASK},
    {SQL_BOOKMARK_PERSISTENCE, "SQL_BOOKMARK_PERSISTENCE", SQLINFO_TYPE_BITMASK},
    {SQL_CATALOG_LOCATION, "SQL_CATALOG_LOCATION", SQLINFO_TYPE_INT},
    {SQL_CATALOG_NAME, "SQL_CATALOG_NAME", SQLINFO_TYPE_STRING},
    {SQL_CATALOG_NAME_SEPARATOR, "SQL_CATALOG_NAME_SEPARATOR", SQLINFO_TYPE_STRING},
    {SQL_CATALOG_TERM, "SQL_CATALOG_TERM", SQLINFO_TYPE_STRING},
    {SQL_CATALOG_USAGE, "SQL_CATALOG_USAGE", SQLINFO_TYPE_BITMASK},
    {SQL_COLLATION_SEQ, "SQL_COLLATION_SEQ", SQLINFO_TYPE_STRING},
    {SQL_COLUMN_ALIAS, "SQL_COLUMN_ALIAS", SQLINFO_TYPE_BOOL},
    {SQL_CONCAT_NULL_BEHAVIOR, "SQL_CONCAT_NULL_BEHAVIOR", SQLINFO_TYPE_INT},
    {SQL_CONVERT_BIGINT, "SQL_CONVERT_BIGINT", SQLINFO_TYPE_BITMASK},
    {SQL_CONVERT_BINARY, "SQL_CONVERT_BINARY", SQLINFO_TYPE_BITMASK},
    {SQL_CONVERT_BIT, "SQL_CONVERT_BIT", SQLINFO_TYPE_BITMASK},
    {SQL_CONVERT_CHAR, "SQL_CONVERT_CHAR", SQLINFO_TYPE_BITMASK},
    {SQL_CONVERT_DATE, "SQL_CONVERT_DATE", SQLINFO_TYPE_BITMASK},
    {SQL_CONVERT_DECIMAL, "SQL_CONVERT_DECIMAL", SQLINFO_TYPE_BITMASK},
    {SQL_CONVERT_DOUBLE, "SQL_CONVERT_DOUBLE", SQLINFO_TYPE_BITMASK},
    {SQL_CONVERT_FLOAT, "SQL_CONVERT_FLOAT", SQLINFO_TYPE_BITMASK},
    {SQL_CONVERT_FUNCTIONS, "SQL_CONVERT_FUNCTIONS", SQLINFO_TYPE_BITMASK},
    {SQL_CONVERT_GUID, "SQL_CONVERT_GUID", SQLINFO_TYPE_BITMASK},
    {SQL_CONVERT_INTEGER, "SQL_CONVERT_INTEGER", SQLINFO_TYPE_BITMASK},
    {SQL_CONVERT_INTERVAL_DAY_TIME, "SQL_CONVERT_INTERVAL_DAY_TIME", SQLINFO_TYPE_BITMASK},
    {SQL_CONVERT_INTERVAL_YEAR_MONTH, "SQL_CONVERT_INTERVAL_YEAR_MONTH", SQLINFO_TYPE_BITMASK},
    {SQL_CONVERT_LONGVARBINARY, "SQL_CONVERT_LONGVARBINARY", SQLINFO_TYPE_BITMASK},
    {SQL_CONVERT_LONGVARCHAR, "SQL_CONVERT_LONGVARCHAR", SQLINFO_TYPE_BITMASK},
    {SQL_CONVERT_NUMERIC, "SQL_CONVERT_NUMERIC", SQLINFO_TYPE_BITMASK},
    {SQL_CONVERT_REAL, "SQL_CONVERT_REAL", SQLINFO_TYPE_BITMASK},
    {SQL_CONVERT_SMALLINT, "SQL_CONVERT_SMALLINT", SQLINFO_TYPE_BITMASK},
    {SQL_CONVERT_TIME, "SQL_CONVERT_TIME", SQLINFO_TYPE_BITMASK},
    {SQL_CONVERT_TIMESTAMP, "SQL_CONVERT_TIMESTAMP", SQLINFO_TYPE_BITMASK},
    {SQL_CONVERT_TINYINT, "SQL_CONVERT_TINYINT", SQLINFO_TYPE_BITMASK},
    {SQL_CONVERT_VARBINARY, "SQL_CONVERT_VARBINARY", SQLINFO_TYPE_BITMASK},
    {SQL_CONVERT_VARCHAR, "SQL_CONVERT_VARCHAR", SQLINFO_TYPE_BITMASK},
    {SQL_CONVERT_WCHAR, "SQL_CONVERT_WCHAR", SQLINFO_TYPE_BITMASK},
    {SQL_CONVERT_WLONGVARCHAR, "SQL_CONVERT_WLONGVARCHAR", SQLINFO_TYPE_BITMASK},
    {SQL_CONVERT_WVARCHAR, "SQL_CONVERT_WVARCHAR", SQLINFO_TYPE_BITMASK},
    {SQL_CORRELATION_NAME, "SQL_CORRELATION_NAME", SQLINFO_TYPE_INT},
    {SQL_CREATE_ASSERTION, "SQL_CREATE_ASSERTION", SQLINFO_TYPE_BITMASK},
    {SQL_CREATE_CHARACTER_SET, "SQL_CREATE_CHARACTER_SET", SQLINFO_TYPE_BITMASK},
    {SQL_CREATE_COLLATION, "SQL_CREATE_COLLATION", SQLINFO_TYPE_BITMASK},
    {SQL_CREATE_DOMAIN, "SQL_CREATE_DOMAIN", SQLINFO_TYPE_BITMASK},
    {SQL_CREATE_SCHEMA, "SQL_CREATE_SCHEMA", SQLINFO_TYPE_BITMASK},
    {SQL_CREATE_TABLE, "SQL_CREATE_TABLE", SQLINFO_TYPE_BITMASK},
    {SQL_CREATE_TRANSLATION, "SQL_CREATE_TRANSLATION", SQLINFO_TYPE_BITMASK},
    {SQL_CREATE_VIEW, "SQL_CREATE_VIEW", SQLINFO_TYPE_BITMASK},
    {SQL_CURSOR_COMMIT_BEHAVIOR, "SQL_CURSOR_COMMIT_BEHAVIOR", SQLINFO_TYPE_INT},
    {SQL_CURSOR_ROLLBACK_BEHAVIOR, "SQL_CURSOR_ROLLBACK_BEHAVIOR", SQLINFO_TYPE_INT},
    {SQL_CURSOR_SENSITIVITY, "SQL_CURSOR_SENSITIVITY", SQLINFO_TYPE_INT},
    {SQL_DATABASE_NAME, "SQL_DATABASE_NAME", SQLINFO_TYPE_STRING},
    {SQL_DATA_SOURCE_NAME, "SQL_DATA_SOURCE_NAME", SQLINFO_TYPE_STRING},
    {SQL_DATA_SOURCE_READ_ONLY, "SQL_DATA_SOURCE_READ_ONLY", SQLINFO_TYPE_BOOL},
    {SQL_DATETIME_LITERALS, "SQL_DATETIME_LITERALS", SQLINFO_TYPE_BITMASK},
    {SQL_DBMS_NAME, "SQL_DBMS_NAME", SQLINFO_TYPE_STRING},
    {SQL_DBMS_VER, "SQL_DBMS_VER", SQLINFO_TYPE_STRING},
    {SQL_DDL_INDEX, "SQL_DDL_INDEX", SQLINFO_TYPE_BITMASK},
    {SQL_DEFAULT_TXN_ISOLATION, "SQL_DEFAULT_TXN_ISOLATION", SQLINFO_TYPE_INT},
    {SQL_DESCRIBE_PARAMETER, "SQL_DESCRIBE_PARAMETER", SQLINFO_TYPE_BOOL},
    {SQL_DM_VER, "SQL_DM_VER", SQLINFO_TYPE_STRING},
    {SQL_DRIVER_HDBC, "SQL_DRIVER_HDBC", SQLINFO_TYPE_INT},
    {SQL_DRIVER_HDESC, "SQL_DRIVER_HDESC", SQLINFO_TYPE_INT},
    {SQL_DRIVER_HENV, "SQL_DRIVER_HENV", SQLINFO_TYPE_INT},
    {SQL_DRIVER_HLIB, "SQL_DRIVER_HLIB", SQLINFO_TYPE_INT},
    {SQL_DRIVER_HSTMT, "SQL_DRIVER_HSTMT", SQLINFO_TYPE_INT},
    {SQL_DRIVER_NAME, "SQL_DRIVER_NAME", SQLINFO_TYPE_STRING},
    {SQL_DRIVER_ODBC_VER, "SQL_DRIVER_ODBC_VER", SQLINFO_TYPE_STRING},
    {SQL_DRIVER_VER, "SQL_DRIVER_VER", SQLINFO_TYPE_STRING},
    {SQL_DROP_ASSERTION, "SQL_DROP_ASSERTION", SQLINFO_TYPE_BITMASK},
    {SQL_DROP_CHARACTER_SET, "SQL_DROP_CHARACTER_SET", SQLINFO_TYPE_BITMASK},
    {SQL_DROP_COLLATION, "SQL_DROP_COLLATION", SQLINFO_TYPE_BITMASK},
    {SQL_DROP_DOMAIN, "SQL_DROP_DOMAIN", SQLINFO_TYPE_BITMASK},
    {SQL_DROP_SCHEMA, "SQL_DROP_SCHEMA", SQLINFO_TYPE_BITMASK},
    {SQL_DROP_TABLE, "SQL_DROP_TABLE", SQLINFO_TYPE_BITMASK},
    {SQL_DROP_TRANSLATION, "SQL_DROP_TRANSLATION", SQLINFO_TYPE_BITMASK},
    {SQL_DROP_VIEW, "SQL_DROP_VIEW", SQLINFO_TYPE_BITMASK},
    {SQL_DYNAMIC_CURSOR_ATTRIBUTES1, "SQL_DYNAMIC_CURSOR_ATTRIBUTES1", SQLINFO_TYPE_BITMASK},
    {SQL_DYNAMIC_CURSOR_ATTRIBUTES2, "SQL_DYNAMIC_CURSOR_ATTRIBUTES2", SQLINFO_TYPE_BITMASK},
    {SQL_EXPRESSIONS_IN_ORDERBY, "SQL_EXPRESSIONS_IN_ORDERBY", SQLINFO_TYPE_BOOL},
    {SQL_FETCH_DIRECTION, "SQL_FETCH_DIRECTION", SQLINFO_TYPE_BITMASK},
    {SQL_FILE_USAGE, "SQL_FILE_USAGE", SQLINFO_TYPE_INT},
    {SQL_FORWARD_ONLY_CURSOR_ATTRIBUTES1, "SQL_FORWARD_ONLY_CURSOR_ATTRIBUTES1", SQLINFO_TYPE_BITMASK},
    {SQL_FORWARD_ONLY_CURSOR_ATTRIBUTES2, "SQL_FORWARD_ONLY_CURSOR_ATTRIBUTES2", SQLINFO_TYPE_BITMASK},
    {SQL_GETDATA_EXTENSIONS, "SQL_GETDATA_EXTENSIONS", SQLINFO_TYPE_BITMASK},
    {SQL_GROUP_BY, "SQL_GROUP_BY", SQLINFO_TYPE_INT},
    {SQL_IDENTIFIER_CASE, "SQL_IDENTIFIER_CASE", SQLINFO_TYPE_INT},
    {SQL_IDENTIFIER_QUOTE_CHAR, "SQL_IDENTIFIER_QUOTE_CHAR", SQLINFO_TYPE_STRING},
    {SQL_INDEX_KEYWORDS, "SQL_INDEX_KEYWORDS", SQLINFO_TYPE_BITMASK},
    {SQL_INFO_SCHEMA_VIEWS, "SQL_INFO_SCHEMA_VIEWS", SQLINFO_TYPE_BITMASK},
    {SQL_INSERT_STATEMENT, "SQL_INSERT_STATEMENT", SQLINFO_TYPE_INT},
    {SQL_INTEGRITY, "SQL_INTEGRITY", SQLINFO_TYPE_BOOL},
    {SQL_KEYSET_CURSOR_ATTRIBUTES2, "SQL_KEYSET_CURSOR_ATTRIBUTES2", SQLINFO_TYPE_BITMASK},
    {SQL_KEYWORDS, "SQL_KEYWORDS", SQLINFO_TYPE_STRING},
    {SQL_LIKE_ESCAPE_CLAUSE, "SQL_LIKE_ESCAPE_CLAUSE", SQLINFO_TYPE_BOOL},
    {SQL_LOCK_TYPES, "SQL_LOCK_TYPES", SQLINFO_TYPE_BITMASK},
    {SQL_MAXIMUM_CATALOG_NAME_LENGTH, "SQL_MAXIMUM_CATALOG_NAME_LENGTH", SQLINFO_TYPE_INT},
    {SQL_MAXIMUM_COLUMNS_IN_GROUP_BY, "SQL_MAXIMUM_COLUMNS_IN_GROUP_BY", SQLINFO_TYPE_INT},
    {SQL_MAXIMUM_COLUMNS_IN_INDEX, "SQL_MAXIMUM_COLUMNS_IN_INDEX", SQLINFO_TYPE_INT},
    {SQL_MAXIMUM_COLUMNS_IN_ORDER_BY, "SQL_MAXIMUM_COLUMNS_IN_ORDER_BY", SQLINFO_TYPE_INT},
    {SQL_MAXIMUM_COLUMNS_IN_SELECT, "SQL_MAXIMUM_COLUMNS_IN_SELECT", SQLINFO_TYPE_INT},
    {SQL_MAXIMUM_COLUMN_NAME_LENGTH, "SQL_MAXIMUM_COLUMN_NAME_LENGTH", SQLINFO_TYPE_INT},
    {SQL_MAXIMUM_CONCURRENT_ACTIVITIES, "SQL_MAXIMUM_CONCURRENT_ACTIVITIES", SQLINFO_TYPE_INT},
    {SQL_MAXIMUM_CURSOR_NAME_LENGTH, "SQL_MAXIMUM_CURSOR_NAME_LENGTH", SQLINFO_TYPE_INT},
    {SQL_MAXIMUM_DRIVER_CONNECTIONS, "SQL_MAXIMUM_DRIVER_CONNECTIONS", SQLINFO_TYPE_INT},
    {SQL_MAXIMUM_IDENTIFIER_LENGTH, "SQL_MAXIMUM_IDENTIFIER_LENGTH", SQLINFO_TYPE_INT},
    {SQL_MAXIMUM_INDEX_SIZE, "SQL_MAXIMUM_INDEX_SIZE", SQLINFO_TYPE_INT},
    {SQL_MAXIMUM_ROW_SIZE, "SQL_MAXIMUM_ROW_SIZE", SQLINFO_TYPE_INT},
    {SQL_MAXIMUM_SCHEMA_NAME_LENGTH, "SQL_MAXIMUM_SCHEMA_NAME_LENGTH", SQLINFO_TYPE_INT},
    {SQL_MAXIMUM_STATEMENT_LENGTH, "SQL_MAXIMUM_STATEMENT_LENGTH", SQLINFO_TYPE_INT},
    {SQL_MAXIMUM_TABLES_IN_SELECT, "SQL_MAXIMUM_TABLES_IN_SELECT", SQLINFO_TYPE_INT},
    {SQL_MAXIMUM_USER_NAME_LENGTH, "SQL_MAXIMUM_USER_NAME_LENGTH", SQLINFO_TYPE_INT},
    {SQL_MAX_ASYNC_CONCURRENT_STATEMENTS, "SQL_MAX_ASYNC_CONCURRENT_STATEMENTS", SQLINFO_TYPE_INT},
    {SQL_MAX_BINARY_LITERAL_LEN, "SQL_MAX_BINARY_LITERAL_LEN", SQLINFO_TYPE_INT},
    {SQL_MAX_CATALOG_NAME_LEN, "SQL_MAX_CATALOG_NAME_LEN", SQLINFO_TYPE_INT},
    {SQL_MAX_CHAR_LITERAL_LEN, "SQL_MAX_CHAR_LITERAL_LEN", SQLINFO_TYPE_INT},
    {SQL_MAX_COLUMNS_IN_GROUP_BY, "SQL_MAX_COLUMNS_IN_GROUP_BY", SQLINFO_TYPE_INT},
    {SQL_MAX_COLUMNS_IN_INDEX, "SQL_MAX_COLUMNS_IN_INDEX", SQLINFO_TYPE_INT},
    {SQL_MAX_COLUMNS_IN_ORDER_BY, "SQL_MAX_COLUMNS_IN_ORDER_BY", SQLINFO_TYPE_INT},
    {SQL_MAX_COLUMNS_IN_SELECT, "SQL_MAX_COLUMNS_IN_SELECT", SQLINFO_TYPE_INT},
    {SQL_MAX_COLUMNS_IN_TABLE, "SQL_MAX_COLUMNS_IN_TABLE", SQLINFO_TYPE_INT},
    {SQL_MAX_COLUMN_NAME_LEN, "SQL_MAX_COLUMN_NAME_LEN", SQLINFO_TYPE_INT},
    {SQL_MAX_CONCURRENT_ACTIVITIES, "SQL_MAX_CONCURRENT_ACTIVITIES", SQLINFO_TYPE_INT},
    {SQL_MAX_CURSOR_NAME_LEN, "SQL_MAX_CURSOR_NAME_LEN", SQLINFO_TYPE_INT},
    {SQL_MAX_DRIVER_CONNECTIONS, "SQL_MAX_DRIVER_CONNECTIONS", SQLINFO_TYPE_INT},
    {SQL_MAX_IDENTIFIER_LEN, "SQL_MAX_IDENTIFIER_LEN", SQLINFO_TYPE_INT},
    {SQL_MAX_INDEX_SIZE, "SQL_MAX_INDEX_SIZE", SQLINFO_TYPE_INT},
    {SQL_MAX_OWNER_NAME_LEN, "SQL_MAX_OWNER_NAME_LEN", SQLINFO_TYPE_INT},
    {SQL_MAX_PROCEDURE_NAME_LEN, "SQL_MAX_PROCEDURE_NAME_LEN", SQLINFO_TYPE_INT},
    {SQL_MAX_QUALIFIER_NAME_LEN, "SQL_MAX_QUALIFIER_NAME_LEN", SQLINFO_TYPE_INT},
    {SQL_MAX_ROW_SIZE, "SQL_MAX_ROW_SIZE", SQLINFO_TYPE_INT},
    {SQL_MAX_ROW_SIZE_INCLUDES_LONG, "SQL_MAX_ROW_SIZE_INCLUDES_LONG", SQLINFO_TYPE_BOOL},
    {SQL_MAX_SCHEMA_NAME_LEN, "SQL_MAX_SCHEMA_NAME_LEN", SQLINFO_TYPE_INT},
    {SQL_MAX_STATEMENT_LEN, "SQL_MAX_STATEMENT_LEN", SQLINFO_TYPE_INT},
    {SQL_MAX_TABLES_IN_SELECT, "SQL_MAX_TABLES_IN_SELECT", SQLINFO_TYPE_INT},
    {SQL_MAX_TABLE_NAME_LEN, "SQL_MAX_TABLE_NAME_LEN", SQLINFO_TYPE_INT},
    {SQL_MAX_USER_NAME_LEN, "SQL_MAX_USER_NAME_LEN", SQLINFO_TYPE_INT},
    {SQL_MULT_RESULT_SETS, "SQL_MULT_RESULT_SETS", SQLINFO_TYPE_BOOL},
    {SQL_NEED_LONG_DATA_LEN, "SQL_NEED_LONG_DATA_LEN", SQLINFO_TYPE_BOOL},
    {SQL_NON_NULLABLE_COLUMNS, "SQL_NON_NULLABLE_COLUMNS", SQLINFO_TYPE_INT},
    {SQL_NULL_COLLATION, "SQL_NULL_COLLATION", SQLINFO_TYPE_INT},
    {SQL_NUMERIC_FUNCTIONS, "SQL_NUMERIC_FUNCTIONS", SQLINFO_TYPE_BITMASK},
    {SQL_ODBC_API_CONFORMANCE, "SQL_ODBC_API_CONFORMANCE", SQLINFO_TYPE_INT},
    {SQL_ODBC_INTERFACE_CONFORMANCE, "SQL_ODBC_INTERFACE_CONFORMANCE", SQLINFO_TYPE_INT},
    {SQL_ODBC_SAG_CLI_CONFORMANCE, "SQL_ODBC_SAG_CLI_CONFORMANCE", SQLINFO_TYPE_INT},
    {SQL_ODBC_SQL_CONFORMANCE, "SQL_ODBC_SQL_CONFORMANCE", SQLINFO_TYPE_INT},
    {SQL_ODBC_SQL_OPT_IEF, "SQL_ODBC_SQL_OPT_IEF", SQLINFO_TYPE_BOOL},
    {SQL_ODBC_VER, "SQL_ODBC_VER", SQLINFO_TYPE_STRING},
    {SQL_OJ_CAPABILITIES, "SQL_OJ_CAPABILITIES", SQLINFO_TYPE_BITMASK}, // = OUTER_JOIN_CAPABILITIES
    {SQL_ORDER_BY_COLUMNS_IN_SELECT, "SQL_ORDER_BY_COLUMNS_IN_SELECT", SQLINFO_TYPE_BOOL},
    {SQL_OUTER_JOINS, "SQL_OUTER_JOINS", SQLINFO_TYPE_BOOL},
    {SQL_OUTER_JOIN_CAPABILITIES, "SQL_OUTER_JOIN_CAPABILITIES", SQLINFO_TYPE_BITMASK}, // alias of SQL_OJ_CAPABILITIES
    {SQL_OWNER_TERM, "SQL_OWNER_TERM", SQLINFO_TYPE_STRING},
    {SQL_OWNER_USAGE, "SQL_OWNER_USAGE", SQLINFO_TYPE_BITMASK},
    {SQL_PARAM_ARRAY_ROW_COUNTS, "SQL_PARAM_ARRAY_ROW_COUNTS", SQLINFO_TYPE_INT},
    {SQL_PARAM_ARRAY_SELECTS, "SQL_PARAM_ARRAY_SELECTS", SQLINFO_TYPE_INT},
    {SQL_POSITIONED_STATEMENTS, "SQL_POSITIONED_STATEMENTS", SQLINFO_TYPE_BITMASK},
    {SQL_POS_OPERATIONS, "SQL_POS_OPERATIONS", SQLINFO_TYPE_BITMASK},
    {SQL_PROCEDURES, "SQL_PROCEDURES", SQLINFO_TYPE_BOOL},
    {SQL_PROCEDURE_TERM, "SQL_PROCEDURE_TERM", SQLINFO_TYPE_STRING},
    {SQL_QUALIFIER_LOCATION, "SQL_QUALIFIER_LOCATION", SQLINFO_TYPE_INT},
    {SQL_QUALIFIER_NAME_SEPARATOR, "SQL_QUALIFIER_NAME_SEPARATOR", SQLINFO_TYPE_STRING},
    {SQL_QUALIFIER_TERM, "SQL_QUALIFIER_TERM", SQLINFO_TYPE_STRING},
    {SQL_QUALIFIER_USAGE, "SQL_QUALIFIER_USAGE", SQLINFO_TYPE_BITMASK},
    {SQL_QUOTED_IDENTIFIER_CASE, "SQL_QUOTED_IDENTIFIER_CASE", SQLINFO_TYPE_INT},
    {SQL_ROW_UPDATES, "SQL_ROW_UPDATES", SQLINFO_TYPE_BOOL},
    {SQL_SCHEMA_TERM, "SQL_SCHEMA_TERM", SQLINFO_TYPE_STRING},
    {SQL_SCHEMA_USAGE, "SQL_SCHEMA_USAGE", SQLINFO_TYPE_BITMASK},
    {SQL_SCROLL_CONCURRENCY, "SQL_SCROLL_CONCURRENCY", SQLINFO_TYPE_BITMASK},
    {SQL_SCROLL_OPTIONS, "SQL_SCROLL_OPTIONS", SQLINFO_TYPE_BITMASK},
    {SQL_SEARCH_PATTERN_ESCAPE, "SQL_SEARCH_PATTERN_ESCAPE", SQLINFO_TYPE_STRING},
    {SQL_SERVER_NAME, "SQL_SERVER_NAME", SQLINFO_TYPE_STRING},
    {SQL_SPECIAL_CHARACTERS, "SQL_SPECIAL_CHARACTERS", SQLINFO_TYPE_STRING},
    {SQL_SQL92_DATETIME_FUNCTIONS, "SQL_SQL92_DATETIME_FUNCTIONS", SQLINFO_TYPE_BITMASK},
    {SQL_SQL92_FOREIGN_KEY_DELETE_RULE, "SQL_SQL92_FOREIGN_KEY_DELETE_RULE", SQLINFO_TYPE_BITMASK},
    {SQL_SQL92_FOREIGN_KEY_UPDATE_RULE, "SQL_SQL92_FOREIGN_KEY_UPDATE_RULE", SQLINFO_TYPE_BITMASK},
    {SQL_SQL92_GRANT, "SQL_SQL92_GRANT", SQLINFO_TYPE_BITMASK},
    {SQL_SQL92_NUMERIC_VALUE_FUNCTIONS, "SQL_SQL92_NUMERIC_VALUE_FUNCTIONS", SQLINFO_TYPE_BITMASK},
    {SQL_SQL92_PREDICATES, "SQL_SQL92_PREDICATES", SQLINFO_TYPE_BITMASK},
    {SQL_SQL92_RELATIONAL_JOIN_OPERATORS, "SQL_SQL92_RELATIONAL_JOIN_OPERATORS", SQLINFO_TYPE_BITMASK},
    {SQL_SQL92_REVOKE, "SQL_SQL92_REVOKE", SQLINFO_TYPE_BITMASK},
    {SQL_SQL92_ROW_VALUE_CONSTRUCTOR, "SQL_SQL92_ROW_VALUE_CONSTRUCTOR", SQLINFO_TYPE_BITMASK},
    {SQL_SQL92_STRING_FUNCTIONS, "SQL_SQL92_STRING_FUNCTIONS", SQLINFO_TYPE_BITMASK},
    {SQL_SQL92_VALUE_EXPRESSIONS, "SQL_SQL92_VALUE_EXPRESSIONS", SQLINFO_TYPE_BITMASK},
    {SQL_SQL_CONFORMANCE, "SQL_SQL_CONFORMANCE", SQLINFO_TYPE_INT},
    {SQL_STANDARD_CLI_CONFORMANCE, "SQL_STANDARD_CLI_CONFORMANCE", SQLINFO_TYPE_INT},
    {SQL_STATIC_CURSOR_ATTRIBUTES1, "SQL_STATIC_CURSOR_ATTRIBUTES1", SQLINFO_TYPE_BITMASK},
    {SQL_STATIC_CURSOR_ATTRIBUTES2, "SQL_STATIC_CURSOR_ATTRIBUTES2", SQLINFO_TYPE_BITMASK},
    {SQL_STATIC_SENSITIVITY, "SQL_STATIC_SENSITIVITY", SQLINFO_TYPE_INT},
    {SQL_STRING_FUNCTIONS, "SQL_STRING_FUNCTIONS", SQLINFO_TYPE_BITMASK},
    {SQL_SUBQUERIES, "SQL_SUBQUERIES", SQLINFO_TYPE_BITMASK},
    {SQL_SYSTEM_FUNCTIONS, "SQL_SYSTEM_FUNCTIONS", SQLINFO_TYPE_BITMASK},
    {SQL_TABLE_TERM, "SQL_TABLE_TERM", SQLINFO_TYPE_STRING},
    {SQL_TIMEDATE_ADD_INTERVALS, "SQL_TIMEDATE_ADD_INTERVALS", SQLINFO_TYPE_BITMASK},
    {SQL_TIMEDATE_DIFF_INTERVALS, "SQL_TIMEDATE_DIFF_INTERVALS", SQLINFO_TYPE_BITMASK},
    {SQL_TIMEDATE_FUNCTIONS, "SQL_TIMEDATE_FUNCTIONS", SQLINFO_TYPE_BITMASK},
    {SQL_TRANSACTION_CAPABLE, "SQL_TRANSACTION_CAPABLE", SQLINFO_TYPE_INT},
    {SQL_TRANSACTION_ISOLATION_OPTION, "SQL_TRANSACTION_ISOLATION_OPTION", SQLINFO_TYPE_BITMASK},
    {SQL_TXN_CAPABLE, "SQL_TXN_CAPABLE", SQLINFO_TYPE_INT},
    {SQL_TXN_ISOLATION_OPTION, "SQL_TXN_ISOLATION_OPTION", SQLINFO_TYPE_BITMASK},
    {SQL_TXN_ISOLATION_OPTION, "SQL_TXN_ISOLATION_OPTION", SQLINFO_TYPE_INT},
    {SQL_TXN_SERIALIZABLE, "SQL_TXN_SERIALIZABLE", SQLINFO_TYPE_INT},
    {SQL_UNION, "SQL_UNION", SQLINFO_TYPE_BITMASK},
    {SQL_USER_NAME, "SQL_USER_NAME", SQLINFO_TYPE_STRING}

    // END
};

void get_sql_error(SQLSMALLINT handle_type, SQLHANDLE handle, char* error, size_t errorsz) {

    SQLCHAR sql_state[6];
    SQLINTEGER native_error;
    SQLCHAR message[SQL_MAX_MESSAGE_LENGTH];
    SQLSMALLINT text_length;
    SQLRETURN rc;
    SQLSMALLINT i = 1;

    rc = SQLGetDiagRec(handle_type, handle, i, sql_state, &native_error, message, sizeof(message), &text_length);
    if (rc == SQL_SUCCESS || rc == SQL_SUCCESS_WITH_INFO) {
        snprintf(error, errorsz, "SQLSTATE %s: %s (Native error %ld)\n", sql_state, message, (long)native_error);
    } else {
        error = "No diagnostic record found.";
    }
}

void bitmask_to_sum_string(SQLUINTEGER mask, char* out, size_t outsz) {

    size_t n = 0;
    out[0] = '\0';
    for (int b = 0; b < 32; b++) {
        SQLUINTEGER v = (SQLUINTEGER)1u << b;
        if (mask & v) {
            int wrote = 0;
            if (n == 0) {
                wrote = snprintf(out + n, outsz - n, "%u", (unsigned)v);
            } else {
                wrote = snprintf(out + n, outsz - n, "+%u", (unsigned)v);
            }
            if (wrote < 0 || (size_t)wrote >= outsz - n) {
                out[outsz - 1] = '\0';
                return;
            }
            n += (size_t)wrote;
        }
    }
    if (n == 0) {
        snprintf(out, outsz, "0");
    }
}

int main(int argc, char** argv) {

    SQLHENV henv = SQL_NULL_HENV;
    SQLHDBC hdbc = SQL_NULL_HDBC;

    if (SQLAllocHandle(SQL_HANDLE_ENV, SQL_NULL_HANDLE, &henv) != SQL_SUCCESS) {
        fprintf(stderr, "SQLAllocHandle ENV failed\n");
        return 1;
    }

    SQLSetEnvAttr(henv, SQL_ATTR_ODBC_VERSION, (void*)SQL_OV_ODBC3, 0);

    if (SQLAllocHandle(SQL_HANDLE_DBC, henv, &hdbc) != SQL_SUCCESS) {
        fprintf(stderr, "SQLAllocHandle DBC failed\n");
        return 1;
    }

    if (SQLDriverConnect(hdbc, NULL, NULL, SQL_NTS, NULL, 0, NULL, SQL_DRIVER_COMPLETE) != SQL_SUCCESS) {
        fprintf(stderr, "SQLDriverConnect failed\n");
        SQLFreeHandle(SQL_HANDLE_DBC, hdbc);
        SQLFreeHandle(SQL_HANDLE_ENV, henv);
        return 1;
    }

    for (int i = 0; items[i].name; i++) {

        SQLUSMALLINT code = items[i].code;
        SQLCHAR* name = items[i].name;
        SQLINFO_TYPE type = items[i].type;
        SQLRETURN rc;
        SQLCHAR error[1024];
        SQLUSMALLINT flag = 0;

        switch (type) {
            case SQLINFO_TYPE_STRING: {

                SQLCHAR buf[1024];
                memset(buf, 0, sizeof(buf));

                rc = SQLGetInfo(hdbc, code, (SQLPOINTER)buf, sizeof(buf), NULL);

                if (SQL_SUCCEEDED(rc)) {
                    printf("%-35s (%u) \t = %s\n", name, code, (char*)buf);
                } else {
                    get_sql_error(SQL_HANDLE_DBC, hdbc, (SQLPOINTER)error, sizeof(error));
                    printf("%-35s (%u) \t = %s\n", name, code, (char*)error);
                }

                break;
            }

            case SQLINFO_TYPE_BOOL: {

                rc = SQLGetInfo(hdbc, code, (SQLPOINTER)&flag, sizeof(flag), NULL);

                if (SQL_SUCCEEDED(rc)) {
                    printf("%-35s (%u) \t = %s\n", name, code, flag ? "TRUE" : "FALSE");
                } else {
                    get_sql_error(SQL_HANDLE_DBC, hdbc, (SQLPOINTER)error, sizeof(error));
                    printf("%-35s (%u) \t = %s\n", name, code, (char*)error);
                }

                break;
            }

            case SQLINFO_TYPE_INT: {

                SQLUSMALLINT flag = 0;
                rc = SQLGetInfo(hdbc, code, (SQLPOINTER)&flag, sizeof(flag), NULL);

                if (SQL_SUCCEEDED(rc)) {
                    printf("%-35s (%u) \t = %u\n", name, code, (unsigned)flag);
                } else {
                    get_sql_error(SQL_HANDLE_DBC, hdbc, (SQLPOINTER)error, sizeof(error));
                    printf("%-35s (%u) \t = %s\n", name, code, (char*)error);
                }

                break;
            }

            case SQLINFO_TYPE_BITMASK: {

                SQLUINTEGER mask = 0;
                SQLUSMALLINT flag = 0;

                rc = SQLGetInfo(hdbc, code, (SQLPOINTER)&mask, sizeof(mask), NULL);

                if (SQL_SUCCEEDED(rc)) {

                    char sum_expr[256];
                    bitmask_to_sum_string(mask, sum_expr, sizeof(sum_expr));

                    unsigned int total = 0;
                    for (int b = 0; b < 32; b++) {
                        if (mask & ((SQLUINTEGER)1 << b)) {
                            total += (1u << b);
                        }
                    }

                    printf("%-35s (%u) \t = 0x%08X  (%s = %u)\n", name, code, (unsigned)mask, sum_expr, total);

                } else {
                    get_sql_error(SQL_HANDLE_DBC, hdbc, (SQLPOINTER)error, sizeof(error));
                    printf("%-35s (%u) \t = %s\n", name, code, (char*)error);
                }

                break;
            }

            default: {
                printf("%-35s (%u) = [UNKNOWN TYPE]\n", name, code);
                break;
            }
        }
    }

    printf("---- DONE ----\n");

    SQLFreeHandle(SQL_HANDLE_DBC, hdbc);
    SQLFreeHandle(SQL_HANDLE_ENV, henv);

    return 0;
}
